[package]
name = "hrafnix"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
clap.workspace = true
hrafnix_shareable_string.workspace = true
hrafnix_translation.workspace = true

[lints]
workspace = true
