[package]
name = "datastore"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = []
hotpath = ["dep:hotpath", "hotpath/hotpath"]
hotpath-alloc = ["hotpath", "hotpath/hotpath-alloc"]

[dependencies]
blake3.workspace = true
serde.workspace = true

hotpath = { workspace = true, optional = true }

shareable_string.workspace = true
keys.workspace = true
message.workspace = true
units.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
