name: Rust - Lint
on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  rust-lint:
    runs-on: ubuntu-24.04
    env:
      RUSTFLAGS: -D warnings
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Update Rust
        run: rustup update
      - name: Add Clippy
        run: rustup component add clippy
      - name: Rust Format check
        run: cargo fmt -- --check
      - name: Rust Clippy check
        run: cargo clippy --workspace --all-targets --all-features --locked
