name: Rust - Lint
on: [ pull_request ]
jobs:
  rust-lint:
    runs-on: ubuntu-24.04
    env:
      RUSTFLAGS: -D warnings
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Update Rust
        run: rustup update
      - name: Add Clippy
        run: rustup component add clippy
      - name: Build Rust project
        run: cargo build
      - name: Rust Format check
        run: cargo fmt -- --check
      - name: Rust Clippy check
        run: cargo clippy
