name: Rust - Cargo Machete
on: [ pull_request ]
jobs:
  rust-cargo-machete:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Machete
        uses: bnjbvr/cargo-machete@main
